### ISSUE TITLE
Save WHOIS Data in User Account

### ISSUE THREAD

**Issue by bhaweshchaudhary** [bhaweshchaudhary/nominet#3]
### Description:

Enable the system to save WHOIS data to a user’s account after each WHOIS lookup. The saved data should be linked to the user’s profile for future reference and periodic monitoring.

### Tasks:

 - [] Create a model to store WHOIS data linked to the user account.
 - [] Implement API endpoint to save WHOIS data to the user’s account.
 - [] Ensure data is stored securely and is accessible to the user.
 - [] Add documentation for the WHOIS data storage feature.
